version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY=API_KEY
    # volumes:
    #   - ./data:/app/data
    command: uvicorn api:app --host 0.0.0.0 --port 8081
    ports:
      - "8081:8081"
